"""create departments table

Revision ID: 79a1c330f0fd
Revises: 8d42f7950fc5
Create Date: 2026-07-12 07:33:02.062014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a1c330f0fd'
down_revision: Union[str, Sequence[str], None] = '8d42f7950fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column(
    "status",
    sa.Enum(
        "DRAFT",
        "PUBLISHED",
        "ARCHIVED",
        name="statusenum",
        create_type=False
    ),
    nullable=False
),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'code', name='uq_exam_department'),
    sa.UniqueConstraint('exam_id', 'slug', name='uq_exam_department_slug')
    )
    op.create_index(op.f('ix_departments_exam_id'), 'departments', ['exam_id'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_slug'), 'departments', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_slug'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_exam_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
