"""create mock test attempt tables

Revision ID: 9e7c553db4a8
Revises: 6fc87f09c3d4
Create Date: 2026-09-05 12:35:39.849407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9e7c553db4a8'
down_revision: Union[str, Sequence[str], None] = '6fc87f09c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_test_attempts',
    sa.Column('mock_test_id', sa.Integer(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('scored_marks', sa.Float(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('unanswered_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mock_test_id'], ['mock_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_test_attempts_id'), 'mock_test_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_mock_test_attempts_mock_test_id'), 'mock_test_attempts', ['mock_test_id'], unique=False)
    op.create_table('mock_test_attempt_answers',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('submitted_answer', sa.String(length=255), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('marks_awarded', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['mock_test_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_test_attempt_answers_attempt_id'), 'mock_test_attempt_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_mock_test_attempt_answers_id'), 'mock_test_attempt_answers', ['id'], unique=False)
    op.create_index(op.f('ix_mock_test_attempt_answers_question_id'), 'mock_test_attempt_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###
    #
    # Note: autogenerate also proposed dropping `temporary_uploads` and
    # renaming a few unrelated constraints (admins/exams/mock_test_questions).
    # Those reflect pre-existing drift between the live database and this
    # repo's models/migrations - unrelated to mock test attempts, so left
    # out of this migration rather than applied as a side effect here.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mock_test_attempt_answers_question_id'), table_name='mock_test_attempt_answers')
    op.drop_index(op.f('ix_mock_test_attempt_answers_id'), table_name='mock_test_attempt_answers')
    op.drop_index(op.f('ix_mock_test_attempt_answers_attempt_id'), table_name='mock_test_attempt_answers')
    op.drop_table('mock_test_attempt_answers')
    op.drop_index(op.f('ix_mock_test_attempts_mock_test_id'), table_name='mock_test_attempts')
    op.drop_index(op.f('ix_mock_test_attempts_id'), table_name='mock_test_attempts')
    op.drop_table('mock_test_attempts')
    # ### end Alembic commands ###
